In [52]:
import pandas as pd 
import numpy as np
#import networkx as nx
import os 
import matplotlib.pyplot as plt 
import RNA
import ast
import pickle
import subprocess

In [69]:
def ens_defect(sequence,target) : 

        fc = RNA.fold_compound(sequence)
        fc.pf()
        fc.bpp()
        ed = fc.ensemble_defect(target)
        return ed

# RFAM Dataset

In [21]:
rfam = pd.read_csv("../../data/rfam/rfam.csv")

ordered_dt = []
for row in rfam.values : 
    ordered_dt.append([row[1], len(row[2]), row[2], row[3]])

In [26]:
ordered_dtsv = pd.DataFrame(ordered_dt, columns=['id','length','target','dataset'])
ordered_dtsv.sort_values(by='length').to_csv('../../data/rfam/sorted_rfam.csv')

In [30]:
sorted_rfam = pd.read_csv("../../data/rfam/sorted_rfam.csv")
sorted_rfam

Unnamed: 0  id  length                                             target  \
0           36   8      54  .((((((.(((((...))))).......((((........)))).....   
1           24   1      65  ((((((....(((((((((.......(((...))).........))...   
2           41  28      73  ..((((((((.(((((....)))))...))))))))..((((.((....   
3           34   5      74  (((((((..((((.........)))).(((((.......))))).....   
4           40  26      79  ((((((.(((((((((((((((((((((..((((...))))........   
5           25   2      79  ((((((.((...((((((...))))))..)))))))).....((((...   
6           37  19      83  ((((((((.((..((((((((....(((.((.....)).))).......   
7           38  14      87  ...(((((((.....)))))))...(((((.((((((((.....))...   
8           35   6      89  .(((((.....((((.((((.......((((..................   
9           39  25     102  (((((......))).))................................   
10          43   1     117  (((((((((....((.(((((...((..((((((.......))..)...   
11          44  21     118  ........((((.(((((.((((((((((((...))))))....))...   
12          42  20     119  ..((((..(((((((((((..........((((((((............   
13          26   3     122  ...((((((....((((((((.........(((...(....).......   
14          46  16     129  (((((((((........................................   
15          45  15     140  ................((.(((((.(((................))...   
16          47  22     148  ........((((..((....((((((..((((((((....))))))...   
17          49   2     151  ........................................((((((...   
18          48   7     154  ...(((((..........)))))........((((((((......)...   
19          50   3     161  ...........((((((((((.(((((..........)))))))))...   
20          27   4     166  (((...(((((....)))))...)))...((((((.(((..(((((...   
21          28   5     179  (((((((..(((((((((......))))))))).........))))...   
22          52  13     185  ..(((((((((((((.(((.............((((.((((((......   
23          54   4     193  ......(((.((((....)))).))).......................   
24          53  24     210  .....((.((..........(((...(((.....)))....))).....   
25          51  12     215  .................................................   
26          10  24     260  .((((.....(((.(.......((.((((....)))).))..((((...   
27           9  14     264  ......(((.(((((((..........(((.((((.....)))).)...   
28          14  16     289  ......(((.....))).((((((..(((.........((.(((((...   
29          13  20     299  ....((.(((..((((...(((......(((((.......((((.(...   
..         ...  ..     ...                                                ...   
33          57  29     340  .((((((((..((((((((.....(((((((.........((((((...   
34          30   7     340  (((((((((((((..((((.....((((.........(((((.......   
35          56  27     344  ....(((((((((..............)))))))))...(((.......   
36          58   9     348  (((((((..........(((((.........((((((......).)...   
37          11   5     350  .((((((...(((..(((((....(((((....))))))))))......   
38          60  10     357  ((((((((((((((((((.(((((((((...))))))))).........   
39          59  18     360  ....................(((.......)))................   
40          31   8     372  .................................................   
41          32   9     375  (((.(((((((((((((....((((((....))))))............   
42          18   8     376  .....(((((.(((.......(((((((..((...(((((((((((...   
43          61  11     382  ...(((((((((((.((((((........))))))..............   
44          15  17     389  ..((((..(((((((...(((...(((((((((.....))))))))...   
45          16  18     418  .((((((.(((((.((.((((..(((((........)))))..((....   
46          62  23     451  .................((((((((((((..(((((.............   
47          17   7     473  (((((...((((..((..(((((..(((.(((.((((.(((...))...   
48          19  19     491  .....((..(((((((.((..((((((((...))))))))..)).....   
49          20   9     506  ...(((((((.(((((((((...(((.(((..((((((..(((..(...   
50          33  10     583  ......(

# RNAEVOL

In [38]:
rnaevol_rfam = pd.read_csv("../../data/rfam/rnaevol.csv")

rnaevol_rfam_solved = rnaevol_rfam[rnaevol_rfam['status'] !=0]


In [46]:
ordered_solved = []

for row in rnaevol_rfam_solved.values : 
    #print(len(row), row)
    ordered_solved.append([row[0],len(row[1]), row[1],row[2],row[3],row[4],row[5],row[6]])
    
df = pd.DataFrame(ordered_solved, columns=['id','length','structure', 'sequence','mfe','fitness','status','datasetID'])
df.sort_values(by='length').to_csv('../../data/rfam/rnaevol_best52.csv', index=None)

In [47]:
sorted_rnaevol_solved = pd.read_csv('../../data/rfam/rnaevol_best52.csv')

In [60]:
target_toPlot = sorted_rnaevol_solved.values[:,2][:35]

In [61]:
target_toPlot

array(['.((((((.(((((...))))).......((((........))))...)))))).',
       '((((((....(((((((((.......(((...))).........)))))..))))....))))))',
       '..((((((((.(((((....)))))...))))))))..((((.((.................))..)).))..',
       '(((((((..((((.........)))).(((((.......))))).....(((((.......)))))))))))).',
       '((((((.(((((((((((((((((((((..((((...))))...........)))))))))))))))))))))))))))',
       '((((((.((...((((((...))))))..)))))))).....((((((((((....)))))))))).............',
       '((((((((.((..((((((((....(((.((.....)).))).........))))))...))..)))))))))).........',
       '...(((((((.....)))))))...(((((.((((((((.....)))))))).)).))).(((((((.((.....)).)))))))..',
       '.(((((.....((((.((((.......((((.....................(((......)))))))...)))))))).....)))))',
       '(((((......))).)).....................................................................................',
       '(((((((((....((.(((((...((..((((((.......))..))))..))....)))))..))(((.((..(.((....((....)).....))

In [74]:
rnaevol_rfam = []
with open('../../data/rfam/rnaevol_rfam2004', "r") as ft : 
    rnaevol_dt = ft.read().split("\n")
    rnaevol_dt.remove("")
    for strg in rnaevol_dt : 
        df = ast.literal_eval(strg)
        info = []
        for tple in df : 
            rnaevol_rfam.append(tple[0])

In [82]:
len(rnaevol_rfam_eds)

340

In [77]:
rnaevol_rfam_eds = []
rnaevol_rfam_hamming = []
rnaevol_rfam_seqs = []
rnaevol_rfam_mfe = []

for row in rnaevol_rfam : 
    rnaevol_rfam_eds.append(float(row[-1]))
    rnaevol_rfam_mfe.append(float(row[2]))
    rnaevol_rfam_seqs.append(row[0])
    rnaevol_rfam_hamming.append((1-float(row[3]))/float(row[3]))

In [83]:

len(rnaevol_rfam_mfe),len(rnaevol_rfam_eds), len(rnaevol_rfam_hamming),len(rnaevol_rfam_seqs)

(340, 340, 340, 340)

In [113]:
with open("../../data/rfam/rnaevol.rfam.all.ed", 'r') as file_  : 
    data = file_.read()
    rnaevol_seqs = np.array(data.split())[:340]

print(len(rnaevol_seqs))
rnaevol_eds = []
rnaevol_mfes = []
rnaevol_hamming = []

for i in range(len(target_toPlot)-2): 
    row_dt = rnaevol_seqs.reshape(34,10)[i]
    for seq in row_dt : 
        strc, mfe = RNA.fold(seq)
        rnaevol_mfes.append(mfe)
        rnaevol_hamming.append(RNA.hamming_distance(strc, target_toPlot[i]))
        rnaevol_eds.append(ens_defect(seq,target_toPlot[i]))

340


In [117]:
rnaevol_df = pd.DataFrame({
    'id': np.concatenate([[i]*10 for i in range(30)]),
    'Tool': ['rnaevol']*len(rnaevol_rfam_seqs[:300]), 
    'sequences' : rnaevol_rfam_seqs[:300], 
    'mfe': rnaevol_rfam_mfe[:300], 
    'Hamming Distance' : rnaevol_rfam_hamming[:300], 
    'ed': rnaevol_rfam_eds[:300]
})

In [118]:
rnaevol_df

Hamming Distance     Tool        ed  id    mfe  \
0                 0.0  rnaevol  0.000895   0  -28.3   
1                 0.0  rnaevol  0.000896   0  -28.3   
2                 0.0  rnaevol  0.000894   0  -29.1   
3                 0.0  rnaevol  0.000935   0  -28.3   
4                 0.0  rnaevol  0.000901   0  -28.3   
5                 0.0  rnaevol  0.000909   0  -28.3   
6                 0.0  rnaevol  0.000891   0  -28.3   
7                 0.0  rnaevol  0.000910   0  -29.0   
8                 0.0  rnaevol  0.000899   0  -28.3   
9                 0.0  rnaevol  0.000896   0  -29.9   
10                0.0  rnaevol  0.001920   1  -29.4   
11                0.0  rnaevol  0.001905   1  -30.7   
12                0.0  rnaevol  0.002479   1  -30.2   
13                0.0  rnaevol  0.002043   1  -29.6   
14                0.0  rnaevol  0.002029   1  -31.3   
15                0.0  rnaevol  0.002223   1  -31.1   
16                0.0  rnaevol  0.001949   1  -32.1   
17                0.0  rnaevol  0.002037   1  -28.7   
18                0.0  rnaevol  0.001954   1  -31.1   
19                0.0  rnaevol  0.001790   1  -33.3   
20                0.0  rnaevol  0.005352   2  -34.9   
21                0.0  rnaevol  0.027408   2  -29.4   
22                0.0  rnaevol  0.008779   2  -30.7   
23                0.0  rnaevol  0.002080   2  -32.9   
24                0.0  rnaevol  0.006976   2  -33.2   
25                0.0  rnaevol  0.002227   2  -33.5   
26                0.0  rnaevol  0.020135   2  -31.8   
27                0.0  rnaevol  0.001843   2  -36.8   
28                0.0  rnaevol  0.002906   2  -30.5   
29                0.0  rnaevol  0.016203   2  -30.9   
..                ...      ...       ...  ..    ...   
270               0.0  rnaevol  0.027054  27 -100.0   
271               0.0  rnaevol  0.027418  27 -104.6   
272               0.0  rnaevol  0.018336  27 -125.8   
273               0.0  rnaevol  0.034084  27 -111.9   
274               0.0  rnaevol  0.020034  27 -114.6   
275               0.0  rnaevol  0.027202  27 -120.5   
276               0.0  rnaevol  0.027261  27 -113.2   
277               0.0  rnaevol  0.022913  27 -107.1   
278               0.0  rnaevol  0.021203  27 -109.6   
279               0.0  rnaevol  0.022912  27 -121.5   
280               0.0  rnaevol  0.008935  28 -134.5   
281               0.0  rnaevol  0.016074  28 -129.6   
282               0.0  rnaevol  0.013070  28 -141.3   
283               0.0  rnaevol  0.017175  28 -129.4   
284               0.0  rnaevol  0.015338  28 -127.1   
285               0.0  rnaevol  0.007853  28 -143.3   
286               0.0  rnaevol  0.012507  28 -132.7   
287               0.0  rnaevol  0.013834  28 -137.6   
288               0.0  rnaevol  0.011889  28 -139.3   
289               0.0  rnaevol  0.016696  28 -127.4   
290               0.0  rnaevol  0.003939  29 -143.4   
291               0.0  rnaevol  0.005787  29 -140.1   
292               0.0  rnaevol  0.003235  29 -134.7   
293               0.0  rnaevol  0.003225  29 -136.1   
294               0.0  rnaevol  0.003163  29 -155.0   
295               0.0  rnaevol  0.003723  29 -138.2   
296               0.0  rnaevol  0.005897  29 -122.1   
297               0.0  rnaevol  0.042629  29 -117.2   
298               0.0  rnaevol  0.004218  29 -132.7   
299               0.0  rnaevol  0.003366  29 -135.5   

                                             sequences  
0    CGCCGGCAGCGGCACGGCCGCAAAGAAAGCCCAAAAACAAGGGCAA...  
1    AGCGCCCAGCGGCAAAGCCGCAAAAAAAGGCCAAAAAAAAGGCCAA...  
2    AGGGCCCAGCGGCACAGCCGCAAAACAAGGCCAGAAAAAAGGCCAA...  
3    AGCCCCCAGCCGCAAAGCGGCAAAAAAAGCGCAAAUUAAAGCGCAA...  
4    AGCGCCCAGCGCCAAAGGCGCAAAAAAAGCCCAAAAACAAGGGCAA...  
5    AGGGGCCAGCGGCAAAGCCGCAAAAAAAGCGCAAAAAAAAGCGCAA...  
6    AGGCGCCAGCGGCAAUGCCGCAAAAAAAGGCCAAAAAAAAGGCCAA...  
7    AGGGCCCAGCGGCACAGCCGCAAAACAAGCCCAAAAAAAAGGGCAA...  
8    AGCCGGCAGCGCCAAAGGCGCAAAAAAAGCCCAAGAUAAAGGGCAA...  
9    AGCCCCCAGCGCCAGAGGC

# Nupack data 

In [63]:
with open("../../data/rfam/nupack.all.seq", 'r') as file_  : 
    data = file_.read()
    nupack_seqs = np.array(data.split())

In [66]:
nupack_eds = []
nupack_mfes = []
nupack_hamming = []

for i in range(len(target_toPlot)): 
    row_dt = nupack_seqs.reshape(35,10)[i]
    for seq in row_dt : 
        strc, mfe = RNA.fold(seq)
        nupack_mfes.append(mfe)
        nupack_hamming.append(RNA.hamming_distance(strc, target_toPlot[i]))
        nupack_eds.append(ens_defect(seq,target_toPlot[i]))

In [67]:
len(nupack_eds), len(nupack_mfes), len(nupack_hamming)

(350, 350, 350)

In [105]:
nupack_df = pd.DataFrame({
    'id': np.concatenate([[i]*10 for i in range(30)]),
    'Tool': ['nupack']*len(nupack_eds[:300]), 
    'sequences' : nupack_seqs[:300], 
    'mfe': nupack_mfes[:300], 
    'Hamming Distance' : nupack_hamming[:300], 
    'ed': nupack_eds[:300]
})

In [88]:
(rnaevol_df+nupack_df).to_csv('../../data/rfam/all_data_toPlot.csv')

In [120]:
df =rnaevol_df.append(nupack_df)
df.to_csv('../../data/rfam/all_data_toPlot.csv')

# RNAinverse

In [94]:
with open("../../data/rfam/RNAinverse_rfam", 'r') as file_  : 
    data = file_.read()
    rnainverse_seqs = np.array(data.split())

In [96]:
len(rnainverse_seqs)

330

In [97]:
rnainverse_eds = []
rnainverse_mfes = []
rnainverse_hamming = []

for i in range(len(target_toPlot)-2): 
    row_dt = rnainverse_seqs.reshape(33,10)[i]
    for seq in row_dt : 
        strc, mfe = RNA.fold(seq)
        rnainverse_mfes.append(mfe)
        rnainverse_hamming.append(RNA.hamming_distance(strc, target_toPlot[i]))
        rnainverse_eds.append(ens_defect(seq,target_toPlot[i]))

In [103]:
rnainverse_df = pd.DataFrame({
    'id': np.concatenate([[i]*10 for i in range(30)]),
    'Tool': ['rnainverse']*len(rnainverse_eds[:300]), 
    'sequences' : rnainverse_seqs[:300], 
    'mfe': rnainverse_mfes[:300], 
    'Hamming Distance' : rnainverse_hamming[:300], 
    'ed': rnainverse_eds[:300]
})

In [104]:
rnainverse_df

Hamming Distance        Tool        ed  id         mfe  \
0                   0  rnainverse  0.000880   0  -29.900000   
1                   0  rnainverse  0.001279   0  -28.700001   
2                   0  rnainverse  0.001000   0  -29.400000   
3                   0  rnainverse  0.000880   0  -29.900000   
4                   0  rnainverse  0.000889   0  -29.100000   
5                   0  rnainverse  0.015163   0  -23.400000   
6                   0  rnainverse  0.001004   0  -29.200001   
7                   0  rnainverse  0.000908   0  -29.100000   
8                   0  rnainverse  0.000997   0  -28.400000   
9                   0  rnainverse  0.001071   0  -29.299999   
10                  0  rnainverse  0.001968   1  -33.099998   
11                  0  rnainverse  0.001622   1  -33.599998   
12                  0  rnainverse  0.001664   1  -32.700001   
13                  0  rnainverse  0.001711   1  -32.900002   
14                  0  rnainverse  0.001727   1  -32.900002   
15                  0  rnainverse  0.001592   1  -33.900002   
16                  0  rnainverse  0.002443   1  -33.200001   
17                  0  rnainverse  0.001608   1  -34.000000   
18                  0  rnainverse  0.002895   1  -31.900000   
19                  0  rnainverse  0.001667   1  -33.000000   
20                  0  rnainverse  0.002932   2  -36.400002   
21                  0  rnainverse  0.017711   2  -34.400002   
22                  0  rnainverse  0.002117   2  -36.599998   
23                  0  rnainverse  0.002238   2  -36.500000   
24                  0  rnainverse  0.002117   2  -36.599998   
25                  0  rnainverse  0.002102   2  -36.500000   
26                  0  rnainverse  0.002869   2  -36.299999   
27                  0  rnainverse  0.011859   2  -32.599998   
28                  0  rnainverse  0.047682   2  -31.400000   
29                  0  rnainverse  0.051009   2  -32.900002   
..                ...         ...       ...  ..         ...   
270                 0  rnainverse  0.000678  27 -165.899994   
271                 0  rnainverse  0.000833  27 -165.800003   
272                 0  rnainverse  0.000926  27 -164.100006   
273                 0  rnainverse  0.000943  27 -164.399994   
274                 0  rnainverse  0.000572  27 -173.500000   
275                 0  rnainverse  0.000552  27 -169.300003   
276                 0  rnainverse  0.000570  27 -164.600006   
277                 0  rnainverse  0.000834  27 -166.600006   
278                 0  rnainverse  0.000715  27 -164.600006   
279                 0  rnainverse  0.000401  27 -169.699997   
280                 0  rnainverse  0.002362  28 -199.000000   
281                 0  rnainverse  0.002143  28 -206.500000   
282                 0  rnainverse  0.002742  28 -204.500000   
283                 0  rnainverse  0.001458  28 -205.699997   
284                 0  rnainverse  0.001596  28 -206.600006   
285                 0  rnainverse  0.002238  28 -201.000000   
286                 0  rnainverse  0.002368  28 -198.100006   
287                 0  rnainverse  0.002013  28 -206.000000   
288                 0  rnainverse  0.002953  28 -203.699997   
289                 0  rnainverse  0.001309  28 -206.500000   
290                 0  rnainverse  0.000537  29 -192.000000   
291                 0  rnainverse  0.000642  29 -191.300003   
292                 0  rnainverse  0.000499  29 -193.300003   
293                 0  rnainverse  0.000495  29 -192.100006   
294                 0  rnainverse  0.000406  29 -193.399994   
295                 0  rnainverse  0.000423  29 -195.100006   
296                 0  rnainverse  0.000499  29 -193.199997   
297                 0  rnainverse  0.000557  29 -189.500000   
298                 0  rnainverse  0.000644  29 -186.899994   
299                 0  rnainverse  0.000440  29 -192.399994   

                                             sequences  
0    AGGGGCCAGCGGCCUUGCCGCAAAAAAAGCCCGAAA

# ETERNA 100

In [48]:
eterna = pd.read_csv('../../data/eterna/eterna.csv')

## NEMO

In [47]:
def fold(sequence) : 
    rnafold = subprocess.Popen(args=["RNAfold"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = rnafold.communicate(sequence)
    out = out.split()
    strc = out[1]
    mef = list(out[-1]) 
    for char in mef : 
        if char in ["(", ")", " "] : 
            mef.remove(char)
    
    return (strc,float("".join(mef)))

nemo_seqs = []
with open("../../data/eterna/nemo.seqs", "r") as f : 
    data = f.read()
    data = data.split("\n")
    #print data
    for i in range(0,len(data), 2) : 
        nemo_seqs.append(data[i])
    nemo_seqs.remove("")



In [8]:
nemo_seqs

['GGCAUGAAAAAAUGCC',
 'GCGUGUGAAAUAGGGAAAAAAAAUACCUGCUUGUGGCUGCGGUUUGAGGCCCAGAUAAAAUCCCAGAAAAAUGGGAGUGUUUGUGGCCUCAAACCGCUUUCACAAGCCACACACGU',
 'GCUGGGAGGCGGAGACGCCCCCGAGCAAAAAAAAAA',
 'AACAUGAAAGGCCCGGAUUGGGAACAAAAAAGCGGGGAUAACUGAAAAUGGUAGAGCUAAGGCCUACGAAUGCAGAGAAAAAUGCAUUCGUGAAACGGCGCUCUCAAAACCCAGAAAAUUAUCGAUCCGAGAGAAAAAAUCUCGGCCCGAAAAAAGGAAAACCAAUCAGGGCAAAGCUUUCGGACUGUUAAA',
 'UACGGGGGGCUAUCAAAGUAGCUGACGGAGAAAAGUGGGCUAGAUUCACUGCGGGAAACCGAGAAAAUGAACUACUACAAUUCAAAGGGAAACCUUUGAAAA',
 'CUACGCCGGGGGAAAAAAACCCCACCGAAAAAAAAAUAGAAGGGAAAGAGGUGAAAAAAGCCUUGGCGUAGAAAACCGCGGCUGAUCUGAAAAAAAAGAUGCUGAUUAAAAAAAAAAGCUGGUAAUCCGAGAAAAGGAUUGCCGCGGAAAAGCCCCCUGAGACCGAAAAGAAGGUCGCAGGUGGAAAAAACCUGCUAAAAUGUAGAAAAUAUACAUAGGGGGCAAAAUCUCUCCGGCACGGAAAAAAACGUGGAUACGGAAAAAACGUAUCGAAACCGUCGAAAAAAGGCGGGGGGAGAAAAAUUCAAGCAACCGCGAAAAAAAGCGGCGCGGAGAAGAAAUCCGCGGAAGGUGGGGAAAAAACCCGCGCUUGAAAAAA',
 'AGAAAUCGCACCAAAAUGGUCGCCUCAACAGAGAAAAAAAAAUUUGAAAAACGAAAAAAAGAGUUUAAUCUGGGAAAUAAGACAGAAAGAGGCGAUCAAAAACGUCAUGGCAAAAAGGAAAAAAAUA

## SendRNA

In [16]:
folders = range(1,101)
sentrna_result = {}
for i in folders : 
    files = os.listdir("../../data/eterna/sentrna/"+str(i)+"/refined/")
    sequences = []
    for file_ in files : 
        sequences.append(pickle.load(open("../../data/eterna/sentrna/"+str(i)+"/refined/"+str(file_)))[0][-2])
    sentrna_result[i] = sequences



In [17]:
sentrna_result

{1: ['GCAUCAAAAAAGAUGC',
  'GCAUCAAAAAAGAUGC',
  'GCAUCAAAAAAGAUGC',
  'GCAUCAAAAAAGAUGC',
  'GCAUCAAAAAAGAUGC'],
 2: ['GCCUAGCAAAACAGAAAAAAAAAAACUGGCCCACAGUGCUGAUGUCUCGGUGCGCAGAAAGCGCCAAAAAAGGCGCACUGCGCAACCGAGACAUCAGUGCUGUGGGCAAGCUAGGC',
  'GCCGGGCAAAAGAGAAAAAAAAAAACUCCCUCAUCCUGCUUAGACCGACAGCCGGAGAAAGCGUCAAAAAAGACGCACUCCGGACUGUCGGUCUAAGUGGGAUGAGGAAGCCCGGC',
  'GCGUAGCAAAAGAGAAAAAAAAAAACUCCCUCAGAGUGCUUAUAGCUAGCGGCCCAGAAAGGAUCAAAAAAGAUCCACUGGGCACGCUAGCUAUAAGUGCUCUGAGGAAGCUACGC',
  'GCUGCGGAAAAGGGAAAAAAAAAAACCCGCUUCCAGUGCUUAUAUGGGGAGGCUUCGAAACCAUGAAAAAACAUGGACGAAGCACUCCCCAUAUAAGUGCUGGAAGCAACCGCAGC',
  'GCUCAUCAAAACGGAAAAAAAAAAACCGGCUUCGAGUGCGUGUAUAUCUCCGCUUGGAAACCCUCAAAAAAGAGGGACCAAGCAGGAGAUAUACACGUGCUCGAAGCAAGAUGAGC'],
 3: ['GAUGAGAGAUCGAAAGAUCCUCAAUCAAAAAAAAAA',
  'GAUGAGAGAUCGAAAGAUCCUCAAUCAAAAAAAAAA',
  'GAUGAGAGAUCGAAAGAUCCUCAAUCAAAAAAAAAA',
  'GAUGAGAGAUCGAAAGAUCCUCAAUCAAAAAAAAAA',
  'GAUGAGAGAUCGAAAGAUCCUCAAUCAAAAAAAAAA'],
 4: ['GAUCGCUUAGGAUCAGCUUAGAAAAAAAAAAAGAUCAUAUCAGGAAAAAGCG

## RNAinverse 

In [158]:

with open('../../data/eterna/test_RNAinverse.txt') as ft : 
    eterna_rnainverse_seqs = ft.read().split('\n')
eterna_rnainverse_seqs.remove('')

In [172]:
choices = np.random.randint(0,10, 5, replace=False)
print choices

TypeError: randint() got an unexpected keyword argument 'replace'

In [174]:
np.random.choice?

In [178]:
eterna_rnainverse_hams = []
eterna_rnainverse_mfes = []
eterna_rnainverse_strcs = []
eterna_rnainverse_eds = []
rnainverse_ids = []
rnainverse_seqs = []
for i in range(92):
    list_ = np.array(eterna_rnainverse_seqs[:920]).reshape((92,10))[i]
    choices = np.random.choice(range(10), 5, replace=False)
    for c in choices : 
        seq = list_[c]
        rst = fold(seq)
        rnainverse_seqs.append(seq)
        eterna_rnainverse_hams.append(RNA.hamming_distance(eterna['strc'].values[i], rst[0]))
        eterna_rnainverse_strcs.append(rst[0])
        eterna_rnainverse_mfes.append(rst[1])
        rnainverse_ids.append(eterna['id'].values[i])
        eterna_rnainverse_eds.append(ens_defect(seq,eterna['strc'].values[i]))
    

In [179]:
len(rnainverse_seqs)

460

In [180]:
rnainverse_df = pd.DataFrame({
    'id': rnainverse_ids,
    'Tool': ['rnainverse']*len(rnainverse_ids), 
    'sequences' : rnainverse_seqs, 
    'structure':eterna_rnainverse_strcs,
    'mfe': eterna_rnainverse_mfes, 
    'Hamming Distance' : eterna_rnainverse_hams, 
    'ed': eterna_rnainverse_eds
})

In [183]:
i = 0
for list_ in rnainverse_df['Hamming Distance'].values.reshape((92,5)) : 
    if 0 in list_ : 
        print list_
        i +=1

[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[ 6 10  0  0 10]
[0 0 0 0 0]
[ 4 10  8 10  0]
[0 0 2 0 0]
[0 0 0 0 0]
[0 0 0 2 2]
[0 0 0 0 0]
[4 4 0 4 4]
[0 0 0 0 0]
[ 9 12  6  6  0]
[0 0 0 0 2]
[ 0 13  6  6  0]
[2 0 6 0 2]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 2 4]
[2 6 6 0 0]
[8 0 6 2 6]
[ 0  4  2  0 10]
[0 0 0 0 0]
[ 0  0 28  0  0]
[10  4  6  0  0]
[20  6  8  0  0]
[0 4 0 0 0]
[0 0 0 2 0]
[ 0 12  8  0 12]
[0 0 0 0 0]
[ 0  0 10 10  0]
[6 0 6 8 0]
[27 10  0  0  0]
[18  4  0  0  0]
[ 0 10  2 12  0]
[0 0 0 4 0]
[ 0  0  6 15  4]
[10  0  0  0  6]
[18  0 26  0  2]
[ 6  0  0 14  0]
[0 4 0 0 6]
[19 17 19  0  0]
[ 0  2 28  4  0]
[2 0 3 0 0]
[31 25  0 11 31]
[ 0 31  0  0 10]
[ 0 20  8  0  0]
[ 0  0  0 10  0]
[0 0 2 0 0]
[20 24 20  0  0]
[0 0 6 0 0]
[18 20  4  0  4]
[ 0 44  0 25 19]
[0 0 0 0 0]
[0 3 3 2 0]
[0 0 0 0 6]
[ 0 30  0  0 24]
[0 0 0 0 0]
[4 2 0 0 0]
[ 0  6 43  4  0]
[0 4 0 0 0]
[ 0  0 91 28  0]


In [184]:
print i 

63


## ERD

In [9]:
erd_on_eterna_result = []
with open("../../data/eterna/result_erd_on_eterna", 'r') as fi : 
    data = fi.read()
    data = data.split("\n")
    #print data
    i = 0
    sub = []
    #print data
    for elt in data: 
        
        if elt == '' : 
            if len(sub)>0 :     
                erd_on_eterna_result.append(sub)
            sub = []
        else : 
            sub.append(elt)

for elt in erd_on_eterna_result : 
    if len (elt) == 0 : 
        erd_on_eterna_result.remove(elt)
print len(erd_on_eterna_result)

100


In [10]:
erd_on_eterna_result

[['GACAGACUGUCC', 'UCCCUCUGGGAC', 'CUUCGCUGGAGA', 'UGCGUAGCGCAA'],
 ['GACUCUCCUUCGAGUC',
  'GCUGCAUCUCCGCGGC',
  'CGUUCGGAUCAGAAUG',
  'AACACGACACGGUGUU'],
 ['GGGACACCUGCUGCGGC',
  'GGAUUCCCUGGGCAACC',
  'GGGUAACCAGGGGAACC',
  'GCAAUAGCAGCGAGAGC'],
 ['UCUCCCUCCCAAGGAGGAGAGGGAAG',
  'GCGGUGCGCCAAGUGGGACGCACCUU',
  'AAUCAUAGGCGAAGAGCGCUAUGACU',
  'UGGUCGGGGCCAGUUGCUUCCGACAA'],
 ['GCCGCGAGAAGCAAGGGAUAGAGUACCGGC',
  'GCCCCGGACAGGAAGCGAUAUCACAGCGGC',
  'GCCGCUUACUGCAUGGGAUAAAAUACCGGC',
  'GCCGGGAAUACCAACCGAUAACCAAGGGGC'],
 ['CGCGCGGGAGUACUGUGCUCCGCACCGCGCU',
  'AACGCCUGACCGUCACGGUCGCCAAGGCGUG',
  'CGGCUGGGCAACUUUGUUGCGAUACCAGCCC',
  'GUCGCCCGGAAUUAAAUUCCCAGAGGGCGGU'],
 ['NON'],
 ['GCGAAAGCACCAAAUGGGCCGUUAGGAGGGAGACC',
  'GGGAAACCACCACAUGGGGCAUUAGCAGCGAAGGC',
  'GGGAGACCACCGACGGGAGCGAGAGCAGCGAGAGC',
  'GCGUGAGCGGCAAAAGCGGGGGGACCAGGGAAACC'],
 ['ACCACCGGGGAGCGCGUUGGGCACCAAGGAGUAGGG',
  'AGCGGCGGCAAGGGGUAUCGCCGGCAAGCCAAAGCA',
  'GGCACCACCAAGCGCGAUGGGCGGGGCGGAGAAGCG',
  'ACCAGCAGCAAGGUCACCGUCCGG

In [72]:
eterna_erd_hams = []
eterna_erd_mfes = []
eterna_erd_strcs = []
eterna_erd_eds = []
erd_ids = []
for i in range(len(erd_on_eterna_result)): 
    seqs = erd_on_eterna_result[i]
    for seq in seqs : 
        rst = fold(seq)
        eterna_erd_hams.append(RNA.hamming_distance(eterna['strc'].values[i], rst[0]))
        eterna_erd_strcs.append(rst[0])
        eterna_erd_mfes.append(rst[1])
        erd_ids.append(eterna['id'].values[i])
        eterna_erd_eds.append(ens_defect(seq,eterna['strc'].values[i]))
        

In [98]:
erd_df = pd.DataFrame({
    'id': erd_ids,
    'Tool': ['erd']*len(eterna_erd_eds), 
    'sequences' : np.concatenate(erd_on_eterna_result), 
    'structure':eterna_erd_strcs,
    'mfe': eterna_erd_mfes, 
    'Hamming Distance' : eterna_erd_hams, 
    'ed': eterna_erd_eds
})

In [99]:
erd_df

Hamming Distance Tool        ed   id     mfe  \
0                   0  erd  0.088247    8   -1.60   
1                   0  erd  0.041580    8   -3.60   
2                   0  erd  0.382092    8   -0.60   
3                   0  erd  0.061640    8   -2.80   
4                   0  erd  0.003523    1   -5.10   
5                   0  erd  0.002046    1   -6.40   
6                   0  erd  0.017096    1   -3.00   
7                   0  erd  0.037221    1   -3.90   
8                   0  erd  0.136202   23   -2.00   
9                   0  erd  0.217547   23   -0.60   
10                  0  erd  0.132581   23   -2.30   
11                  0  erd  0.154003   23   -1.30   
12                  0  erd  0.170985   26  -12.60   
13                  0  erd  0.008188   26  -13.40   
14                  0  erd  0.047187   26   -8.60   
15                  0  erd  0.076751   26  -10.00   
16                  0  erd  0.171955   15   -3.90   
17                  0  erd  0.211062   15   -3.30   
18                  0  erd  0.186023   15   -3.80   
19                  0  erd  0.251738   15   -4.10   
20                  0  erd  0.080016   30  -14.80   
21                  0  erd  0.037585   30  -14.80   
22                  0  erd  0.003471   30  -14.90   
23                  0  erd  0.057419   30  -12.20   
24                  0  erd -1.000000   88    0.00   
25                  0  erd  0.251482   41   -4.30   
26                  0  erd  0.235782   41   -3.80   
27                  0  erd  0.158985   41   -5.00   
28                  0  erd  0.194539   41   -4.70   
29                  6  erd  0.279217   66   -7.70   
..                ...  ...       ...  ...     ...   
310                 0  erd  0.125772   28 -151.27   
311                 0  erd  0.165158   28 -138.27   
312                 0  erd  0.072383   28 -167.47   
313                 0  erd  0.172982   28 -154.77   
314                 0  erd  0.394377    6 -140.90   
315                 0  erd  0.288692    6 -127.10   
316                 0  erd  0.193306    6 -122.00   
317                 0  erd  0.125693    6 -118.60   
318                 1  erd -1.000000   74    0.00   
319                 0  erd -1.000000  100    0.00   
320                 0  erd  0.121448   56 -200.80   
321                 0  erd  0.065885   56 -172.70   
322                 0  erd  0.047702   56 -185.20   
323                 0  erd  0.026667   56 -216.00   
324                 3  erd -1.000000   94    0.00   
325                 0  erd  0.190237   85 -117.40   
326                 0  erd  0.251982   85 -123.20   
327                 0  erd  0.196308   85 -124.30   
328                 0  erd  0.309740   85 -136.00   
329                 2  erd -1.000000   91    0.00   
330                 3  erd -1.000000   76    0.00   
331                 1  erd -1.000000   80    0.00   
332                 0  erd  0.089465   63 -142.70   
333                 0  erd  0.229984   63 -129.80   
334                 0  erd  0.164051   63 -145.50   
335                 0  erd  0.169113   63 -134.50   
336                 0  erd -1.000000   53    0.00   
337                 0  erd -1.000000   22    0.00   
338                 1  erd -1.000000   97    0.00   
339                 1  erd -1.000000   90    0.00   

                                             sequences  \
0                                         GACAGACUGUCC   
1                                         UCCCUCUGGGAC   
2                                         CUUCGCUGGAGA   
3                                         UGCGUAGCGCAA   
4                                     GACUCUCCUUCGAGUC   
5                                     GCUGCAUCUCCGCGGC   
6                                     CGUUCGGAUCAGAAUG   
7                                     AACACGACACGGUGUU   
8                                    GGGACACCUGCUGCGGC   
9                                    GGAUUCCCUGGGCAACC   
10                                   GGGUAACCAGGGGAACC   
11                    

## RNAEVOL

In [19]:
rnaevol = []
rnaevol_df = pd.read_csv('../../data/eterna/result-eterna-med.csv')

for line in rnaevol_df.values : 
    if type(line[2]) == type("nono"): 
        rnaevol.append(line[1])
print rnaevol

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 53, 54, 55, 56, 58, 59, 62, 63, 66, 69, 70, 72, 75, 77, 82, 83, 84, 93, 95, 98]


In [110]:
 with open('../../data/eterna/eterna_rnaevol') as ft : 
        rnaevol_result = ft.read().split('\n')

rnaevol_result.remove('')

In [129]:
eterna_rnaevol_hams = []
eterna_rnaevol_mfes = []
eterna_rnaevol_strcs = []
eterna_rnaevol_eds = []
eterna_rnaevol_seqs = []
rnaevol_ids = []

for i in range(len(rnaevol_result)) : 
    row = ast.literal_eval(rnaevol_result[i])
    for lst in row : 
        print(lst)
        rnaevol_ids.append(eterna['id'].values[i])
        eterna_rnaevol_mfes.append(lst[0][2])
        eterna_rnaevol_strcs.append(lst[0][1])
        eterna_rnaevol_seqs.append(lst[0][0])
        eterna_rnaevol_eds.append(lst[0][-1])
        eterna_rnaevol_hams.append((1.-float(lst[0][3]))/float(lst[0][3]))

(['GGCCCGGGGCCA', '((((...)))).', '-6.3', '1.0', '0.00274344963964'], 0)
(['GGCCAAAGGCCA', '((((...)))).', '-6.3', '1.0', '0.00275362423932'], 0)
(['GGCCUAUGGCCA', '((((...)))).', '-6.3', '1.0', '0.00273884418207'], 0)
(['GGCCAAUGGCCA', '((((...)))).', '-6.3', '1.0', '0.00274974537803'], 0)
(['GGGCCGAAAAAGGCCC', '(((((......)))))', '-10.2', '1.0', '0.0015713222201'], 0)
(['GGCCCGGGAAAGGGCC', '(((((......)))))', '-10.2', '1.0', '0.00155913089952'], 0)
(['GGCCCGAAAAAGGGCC', '(((((......)))))', '-10.2', '1.0', '0.00155908491459'], 0)
(['GGCCCGAAAAAGGGCC', '(((((......)))))', '-10.2', '1.0', '0.00155908491459'], 0)
(['GCGAAAGCAGGGAAACC', '((....)).((....))', '-2.2', '1.0', '0.076878571113'], 5)
(['GCUACGGCACCGAAAGG', '((....)).((....))', '-2.8', '1.0', '0.0633014821262'], 5)
(['GCGUAAGCACCGACAGG', '((....)).((....))', '-2.3', '1.0', '0.0716574165743'], 5)
(['GCCAAGGCACCGAAAGG', '((....)).((....))', '-2.3', '1.0', '0.0680782020714'], 4)
(['AAGGCCGGCCAAAAAGGACCGGCCAA', '..((((((((.....)).)))

In [130]:
eterna_rnaevol_df = pd.DataFrame({
    'id': rnaevol_ids,
    'Tool': ['rnaevol']*len(rnaevol_ids), 
    'sequences' : eterna_rnaevol_seqs, 
    'structure':eterna_rnaevol_strcs,
    'mfe': eterna_rnaevol_mfes, 
    'Hamming Distance' : eterna_rnaevol_hams, 
    'ed': eterna_rnaevol_eds
})

In [131]:
eterna_rnaevol_df

Hamming Distance     Tool                ed   id     mfe  \
0                 0.0  rnaevol  0.00274344963964    8    -6.3   
1                 0.0  rnaevol  0.00275362423932    8    -6.3   
2                 0.0  rnaevol  0.00273884418207    8    -6.3   
3                 0.0  rnaevol  0.00274974537803    8    -6.3   
4                 0.0  rnaevol   0.0015713222201    1   -10.2   
5                 0.0  rnaevol  0.00155913089952    1   -10.2   
6                 0.0  rnaevol  0.00155908491459    1   -10.2   
7                 0.0  rnaevol  0.00155908491459    1   -10.2   
8                 0.0  rnaevol    0.076878571113   23    -2.2   
9                 0.0  rnaevol   0.0633014821262   23    -2.8   
10                0.0  rnaevol   0.0716574165743   23    -2.3   
11                0.0  rnaevol   0.0680782020714   23    -2.3   
12                0.0  rnaevol  0.00136718344084   26   -15.9   
13                0.0  rnaevol   0.0012133905221   26   -16.5   
14                0.0  rnaevol  0.00103964545113   26   -16.7   
15                0.0  rnaevol  0.00103922039212   26   -16.7   
16                0.0  rnaevol   0.0918583809813   15    -3.3   
17                0.0  rnaevol    0.116585796096   15    -3.3   
18                0.0  rnaevol     0.12547771926   15    -2.9   
19                0.0  rnaevol    0.129708753706   15    -3.3   
20                0.0  rnaevol  0.00126241266838   30   -20.7   
21                0.0  rnaevol  0.00126691547931   30   -20.8   
22                0.0  rnaevol  0.00127753440019   30   -21.5   
23                0.0  rnaevol  0.00126130110432   30   -20.7   
24                2.0  rnaevol     0.10769653561   88    -7.6   
25                2.0  rnaevol     0.10358019952   88   -11.6   
26                2.0  rnaevol   0.0979345956662   88   -13.1   
27                2.0  rnaevol    0.107524510379   88   -11.7   
28                0.0  rnaevol   0.0725206427105   41    -5.1   
29                0.0  rnaevol   0.0733575116256   41    -5.5   
..                ...      ...               ...  ...     ...   
354              26.0  rnaevol    0.262559789619  100   -16.9   
355              24.0  rnaevol    0.229287185359  100   -26.9   
356               0.0  rnaevol  0.00587546133907   56  -254.9   
357               0.0  rnaevol  0.00506486690704   56  -260.4   
358               0.0  rnaevol   0.0038764696718   56  -271.7   
359               0.0  rnaevol  0.00616282428693   56  -269.4   
360              39.0  rnaevol    0.211993032121   94  -165.4   
361              21.0  rnaevol    0.125648334813   94  -149.0   
362              41.0  rnaevol    0.240915916061   94  -169.6   
363              40.0  rnaevol    0.218008813238   94  -152.0   
364              46.0  rnaevol    0.255444564125   85  -119.6   
365              48.0  rnaevol    0.245024125655   85  -136.7   
366              62.0  rnaevol    0.302975629266   85  -135.4   
367              54.0  rnaevol     0.26839069072   85  -132.3   
368              28.0  rnaevol    0.159720146684   91   -90.9   
369              25.0  rnaevol    0.109316578731   91   -78.2   
370              32.0  rnaevol    0.163854363778   91   -97.0   
371              30.0  rnaevol    0.157565344634   91   -92.9   
372              83.0  rnaevol    0.393199000082   76  -156.8   
373              74.0  rnaevol    0.369367353829   76  -134.9   
374              80.0  rnaevol    0.315319632463   76  -155.3   
375              63.0  rnaevol    0.287209927376   76  -183.5   
376               2.0  rnaevol   0.0187826895302   80  -175.6   
377               2.0  rnaevol   0.0222036864099   80  -186.4   
378               2.0  rnaevol   0.0238618185649   80  -183.3   
379               2.0  rnaevol   0.0254002202182   80  -175.8   
380               0.0  rnaevol   0.0118309436299   63  -191.3   
381               0.0  rnaevol    0.022910492282   63  -170.3   
382               0.0  rnaevol   0.0123163782659   63  -193.4   
383               0.0  rnaevol   0.01858

In [28]:
lengths = {}
for key in sentrna_result.keys() : 
    #print(len(sentrna_result[key][0]))
    
    lengths[key] = len(sentrna_result[key][0])

In [63]:

sorted_sentrna_seqs =[]
eterna_ids =[]
for lg in sorted(set(lengths.values())):
    for k in lengths.keys(): 
        if lengths[k] ==lg: 
            sorted_sentrna_seqs.append(sentrna_result[k])
            eterna_ids.append(k)
    
    

In [56]:
eterna_sentrna_mfes = []
eterna_sentrna_strcs = []
for seq in np.concatenate(sorted_sentrna_seqs): 
    rst = fold(seq)
    eterna_sentrna_strcs.append(rst[0])
    eterna_sentrna_mfes.append(rst[1])

In [93]:
eterna_sentrna_hams = []
eterna_sentrna_mfes = []
eterna_sentrna_strcs = []
eterna_sentrna_eds = []
eterna_sentrna_seqs = []
ids = []
for id_ in eterna_ids : 
    for seq in sentrna_result[id_] : 
        rst = fold(seq)
        eterna_sentrna_hams.append(RNA.hamming_distance(eterna[eterna['id']==id_]['strc'].values[0], rst[0]))
        eterna_sentrna_strcs.append(rst[0])
        eterna_sentrna_mfes.append(rst[1])
        ids.append(id_)
        eterna_sentrna_eds.append(ens_defect(seq,eterna[eterna['id']==id_]['strc'].values[0]))
        eterna_sentrna_seqs.append(seq)
        

In [94]:
sentrna_df = pd.DataFrame({
    'id': ids,
    'Tool': ['sentrna']*len(ids), 
    'sequences' : eterna_sentrna_seqs, 
    'structure':eterna_sentrna_strcs,
    'mfe': eterna_sentrna_mfes, 
    'Hamming Distance' : eterna_sentrna_hams, 
    'ed': eterna_sentrna_eds
})

In [95]:
sentrna_df

Hamming Distance     Tool        ed  id    mfe  \
0                   0  sentrna  0.021784   8   -2.2   
1                   0  sentrna  0.021784   8   -2.2   
2                   0  sentrna  0.021784   8   -2.2   
3                   0  sentrna  0.021784   8   -2.2   
4                   0  sentrna  0.021784   8   -2.2   
5                   0  sentrna  0.002101   1   -5.1   
6                   0  sentrna  0.002101   1   -5.1   
7                   0  sentrna  0.002101   1   -5.1   
8                   0  sentrna  0.002101   1   -5.1   
9                   0  sentrna  0.002101   1   -5.1   
10                  0  sentrna  0.154207  23   -0.8   
11                  0  sentrna  0.132980  23   -2.4   
12                  0  sentrna  0.080155  23   -2.3   
13                  0  sentrna  0.082802  23   -2.2   
14                  0  sentrna  0.132980  23   -2.4   
15                  0  sentrna  0.085229  26   -5.5   
16                  0  sentrna  0.085229  26   -5.5   
17                  0  sentrna  0.085229  26   -5.5   
18                  0  sentrna  0.085229  26   -5.5   
19                  0  sentrna  0.085229  26   -5.5   
20                  0  sentrna  0.200470  15   -1.0   
21                  0  sentrna  0.200470  15   -1.0   
22                  0  sentrna  0.167246  15   -1.9   
23                  0  sentrna  0.200470  15   -1.0   
24                  0  sentrna  0.247012  15   -1.9   
25                  0  sentrna  0.002521  30  -11.3   
26                  0  sentrna  0.002521  30  -11.3   
27                  0  sentrna  0.002521  30  -11.3   
28                  0  sentrna  0.002521  30  -11.3   
29                  0  sentrna  0.002521  30  -11.3   
..                ...      ...       ...  ..    ...   
470                 0  sentrna  0.233233  76 -126.3   
471                 0  sentrna  0.255089  76 -126.0   
472                 0  sentrna  0.304419  76 -130.9   
473                52  sentrna  0.259470  76 -137.2   
474                 0  sentrna  0.313938  76 -124.2   
475                 0  sentrna  0.000000  22    0.0   
476                 0  sentrna  0.000000  22    0.0   
477                 0  sentrna  0.000000  22    0.0   
478                 0  sentrna  0.000000  22    0.0   
479                 0  sentrna  0.000000  22    0.0   
480                 0  sentrna  0.137651  53   -2.8   
481                 0  sentrna  0.119085  53   -3.6   
482                 0  sentrna  0.160674  53   -1.0   
483                 0  sentrna  0.146006  53   -1.1   
484                 0  sentrna  0.139049  53   -1.5   
485                 0  sentrna  0.023135  63 -156.9   
486                 0  sentrna  0.016423  63 -154.2   
487                 0  sentrna  0.003625  63 -159.9   
488                 0  sentrna  0.004513  63 -145.7   
489                 0  sentrna  0.005770  63 -160.4   
490                48  sentrna  0.134941  90 -184.8   
491                48  sentrna  0.139300  90 -167.6   
492                48  sentrna  0.140850  90 -161.0   
493                52  sentrna  0.160729  90 -175.6   
494                48  sentrna  0.123195  90 -159.4   
495                27  sentrna  0.132794  97 -126.0   
496                 2  sentrna  0.092129  97 -134.8   
497                 2  sentrna  0.092940  97 -131.6   
498                 2  sentrna  0.064201  97 -140.7   
499                16  sentrna  0.121517  97 -114.1   

                                             sequences  \
0                                         GAUCAAAGAUCA   
1                                         GAUCAAAGAUCA   
2                                         GAUCAAAGAUCA   
3                                         GAUCAAAGAUCA   
4                                         GAUCAAAGAUCA   
5                                     GCAUCAAAAAAGAUGC   
6                                     GCAUCAAAAAAGAUGC   
7                                     GCAUCAAAAAAGAUGC   
8                                     GCAUCAAAAAAGAUGC   
9             

In [145]:
sort = eterna_rnaevol_df[eterna_rnaevol_df['id']==1]

In [206]:
sentrna_founds= [1, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 53, 54, 55, 56, 58, 63, 73, 76, 82, 83, 84, 85, 93, 95, 98]

In [214]:
all_eterna = eterna_rnaevol_df[eterna_rnaevol_df['id']==1]
all_eterna = all_eterna.append(sentrna_df[sentrna_df['id']==1])
all_eterna = all_eterna.append(erd_df[erd_df['id']==1])
all_eterna = all_eterna.append(rnainverse_df[rnainverse_df['id']==1])

for id_ in eterna['id'].values[:32] : 
    
    if id_ not in [1,88,57] : 
        print id_
        all_eterna = all_eterna.append(eterna_rnaevol_df[eterna_rnaevol_df['id']==id_])
        all_eterna = all_eterna.append(sentrna_df[sentrna_df['id']==id_])
        all_eterna = all_eterna.append(erd_df[erd_df['id']==id_])
        all_eterna = all_eterna.append(rnainverse_df[rnainverse_df['id']==id_])

8
23
26
15
30
41
66
11
3
40
65
20
33
10
47
62
27
25
67
44
45
61
13
59
18
72
75
52
95


In [215]:
all_eterna.to_csv('../../data/eterna/all_eterna.csv')

In [216]:
all_eterna[all_eterna['ed']<0]

Empty DataFrame
Columns: [Hamming Distance, Tool, ed, id, mfe, sequences, structure]
Index: []

In [196]:
sentrna_df[sentrna_df['ed']<0]

Hamming Distance     Tool   ed  id    mfe  \
215                68  sentrna -1.0  80  -28.3   
216                66  sentrna -1.0  80  -27.8   
217                68  sentrna -1.0  80  -26.8   
218                67  sentrna -1.0  80  -30.2   
219                67  sentrna -1.0  80  -25.5   
285                 2  sentrna -1.0  77  -40.5   
286                 2  sentrna -1.0  77  -42.4   
287                 2  sentrna -1.0  77  -46.4   
288                 2  sentrna -1.0  77  -46.6   
289                 2  sentrna -1.0  77  -43.0   
290                20  sentrna -1.0  64    0.0   
291                18  sentrna -1.0  64   -0.8   
292                18  sentrna -1.0  64   -0.3   
293                16  sentrna -1.0  64   -0.6   
294                20  sentrna -1.0  64    0.0   
375                63  sentrna -1.0   9  -87.2   
376                63  sentrna -1.0   9  -93.8   
377                63  sentrna -1.0   9  -99.5   
378                63  sentrna -1.0   9  -98.4   
379                63  sentrna -1.0   9  -86.6   
410                56  sentrna -1.0  87 -119.3   
411                57  sentrna -1.0  87 -124.0   
412                52  sentrna -1.0  87 -121.6   
413                57  sentrna -1.0  87 -130.9   
414                57  sentrna -1.0  87 -114.8   

                                             sequences  \
215  AAAAAAGGGCGCAGCCCAAAACAAAGCCCAGAAAACAGGGCAAAGG...   
216  AAAAAAGGCCGGACGGGAAAACAAACGCGAGAAAACACGCGAAAGC...   
217  AAAAAACGGCGCAGGGCAAAAGAAACCCCAGAAAACAGGGGAAACG...   
218  AAAAAACGCCCCAGCGCAAAAGAAAGGGGAGAAAACACCCCAAACG...   
219  AAAAAACGCGCGACGCCAAAACAAAGCGCACAAAAGAGCGCAAAGG...   
285  AAAAAGCCUGGGACCACCGAAAGGUGAGCCCCCUGACGAACGCCGA...   
286  AAAAAGGGUGGGACGACCGAAAGGUCAGCCGGCCCACCAACACGGA...   
287  AAAAACCGGCGGAGGAGCGAAAGCUCACCCGCGCCACGAAGCGGGA...   
288  AAAAAGGGCCGGAGGGUCGAAAGACCACCCGGGCCAGCAAGAGCGA...   
289  AAAAACCGCGGGAGGAUCGAAAGAUCACCCGCGGCACCAACCGGGA...   
290  CCAAAGCAAAAGGAAAAAGCAAAAAAAAACGAAAAAAAAAAAAAAA...   
291  GCAAAGCAAAACGAAAAAGCAAAAAAAAACCAAAAAAAAAAAAAAA...   
292  CGAAAGGAAAACCAAAAACCAAAAAAAAAGCAAAAAAAAAAAAAAA...   
293  GGAAACCAAAAGGAAAAAGCAAAAAAAAACCAAAAAAAAAAAAAAA...   
294  GGAAAGGAAAAGCAAAAACCAAAAAAAAACGAAAAAAAAAAAAAAA...   
375  GCGAGAGGAUCAAAGAUCAACUCCGCAAAGACAGGCGAGCAAAGCU...   
376  GAGAGCCGGCCAAAGGCCAAGGCCUCAAAGACAGACGAGGAAACCU...   
377  CAGAGGGGCUCAAAGAGCAACCCCUGAAAGCGAGGGGAUCAAAGAU...   
378  GAGACAGGGUGAAACACCAACUGCUCAAAGAGACACCAUCAAAGAU...   
379  CACAGGGGAUCAAAGAUCAACCCGUGAAAGACACCCGACCAAAGGU...   
410  AAAAAAACAUGAGGGGACGCACCGGAAACGGAGGCAGAGGAAACUC...   
411  AAAAAAAGGCGAGGGGAGCGACGCGAAAGCGACGGAGACGAAAGUC...   
412  AAAAAAAGGCGACCGCAGCGACCGGAAACGGAGGCAGCCGAAAGGC...   
413  AAAAAAACCGGACGGCACGGAGGGGAAACCCACGGACGCGAAAGCG...   
414  AAAAAAAGCCGAGACGAGGGACGGGAAACCGAGGGAGGGGAAACCC...   

                                             structure  
215  ......(.((((.((((........((((........))))....)...  
216  ......(.((((.((((........((((........))))...((...  
217  ......(.((((.((((........((((........))))....)...  
218  ......(.((((.((((........((((........))))...((...  
219  ......((((((.((((........((((........))))....)...  
285  .....(((((((..((((....))))..))(((((.((..((((.....  
286  .....(((((((..((((....))))..))(((((.((..((((.....  
287  .....(((((((..((((....))))..))(((((.((..((((.....  
288  .....(((((((..((((....))))..))(((((.((..((((.....  
289  .....(((((((..((((....))))..))(((((.((..((((.....  
290  .................................................  
291  .................................................  
292  .....((....))....................................  
293  .....((....))....................................  
294  .................................................  
375  (((.(((((((...))))..))))))...(((.(((((((...)))...  
376  (((.(((((((...))))..))))))...(((.(((((((...)))...  
377  (((.(((((((...))))..))))))...(((.(((((((...)))...  
378  (((.(((((((...))))..))))))...(((.(((((((...)))...  
379  (((.(((((((...))))..))))))...(((.(((((((...)))... 

In [202]:
eterna[eterna['id']==64]['strc'].values

array(['((...((....((.....((.........((..............................))...............)).........)).......))....))...'],
      dtype=object)

In [203]:
sentrna_df[sentrna_df['id']==64]['structure'].values

array(['..............................................................................................................',
       '..................................................................................................((....))....',
       '.....((....)).................................................................................................',
       '.....((....)).....................................................................................((....))....',
       '..............................................................................................................'],
      dtype=object)

In [205]:
len('.....((....)).....................................................................................((....))....')

110